### PR TITLE
Improuvement & Support & New Features

### PR DESCRIPTION
**Pull request by JeanTheFungle**
hey, i was working on tou to make it better and people love it so there the changes that i made :

---
  ### : ✔️ Changes

- Improuvement PingTracker colors, logo, many more...
- Add Custom Logo (LeftBox)
- Add some Custom Hats from The Popular Polus.gg.
- Fast Boot
-  - **Add The Name of the host on Lobby idea from @wichtwix #168**
- -  **Add Support The new [Submerged](https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2023.8.2) 2023.8.2**
-  - **Add new Loader Sprite from [TownOfHostEdited](https://github.com/KARPED1EM/TownOfHostEdited)**

And I hope this get merged or take an idea for the next update of TOU

### CODE REVIEW

**Comment by whichtwix** [comment]
I dont believe taking hats from polus.gg is allowed

**Comment by JeanAU** [comment]
> I dont believe taking hats from polus.gg is allowed

why not polus.gg is open source if not allowed i will remove them

**Comment by whichtwix** [comment]
the hats are copyrighted i think

**Comment by AlchlcDvl** [comment]
yeah that and the fact you need the the original artists' permission to add it, you cannot just add them whenever you'd like

**Comment by JeanAU** [comment]
> yeah that and the fact you need the the original artists' permission to add it, you cannot just add them whenever you'd like

ok i will ask him if let me to add on TOU

**Comment by JeanAU** [comment]
@twix hey, can u merge this to annother branch ? if possible

**Comment by whichtwix** [comment]
no i cant

**Comment by JeanAU** [comment]
> no i cant

why ? is there something i need to do ?

**Comment by whichtwix** [comment]
yes, fix the merge conflicts and wait fotr mdb

**Comment by JeanAU** [comment]
> yes, fix the merge conflicts and wait for mdb

ok idk how thoses conflicting come out

**Comment by JeanTheFungle** [comment]
@MyDragonBreath this pr you will be merged or not ? only features

and i'm gonna open a new pull wich support fungle update

**Comment by AlchlcDvl** [comment]
no

support is already in the works, he doesn't need your help

**Comment by JeanTheFungle** [comment]
> no
> 
> support is already in the works, he doesn't need your help

i didn't talk you.
and my dragon breath always praise for my effort i do

**Comment by JeanTheFungle** [comment]
> dude i am working on the mod with him

really ??? so you are a dev in tou and what's abou tou reworked ?

**Comment by AlchlcDvl** [comment]
it'll still be separate is all i can say

**Comment by JeanTheFungle** [comment]
> it'll still be separate is all i can say
good luck just there will be new features ?

**I wante really join you guys but it's ok**

**Comment by MyDragonBreath** [comment]
I cant add blatant ignorance to copyright laws.
the next release is coming soon, and has been ported already.
the lobby logo is a bit much, i feel like we already have enough branding in the top right, no need to plaster a name there as well.
I did merge the splash screen skipper - but if its against innersloth license i will have to remove it.
Sorry it has taken me so long to get around to you

**Comment by JeanTheFungle** [comment]
> I cant add blatant ignorance to copyright laws. (The polus.gg hats) the next release is coming soon, and has been ported already. the lobby logo is a bit much, i feel like we already have enough branding in the top right, no need to plaster a name there as well. I did merge the splash screen skipper - but if its against innersloth license i will have to remove it. Sorry it has taken me so long to get around to you

thx about splash screen skipper it's not against innersloth because i saw many ohter mods have this functionnality

**Comment by whichtwix** [comment]
does this improve the loading time though?

**Pull request closed without merging**
