### PR TITLE
Update To 2024.3.5 + Support LongMode

### PR DESCRIPTION
**Pull request by SaskueUchiwa**
**hi, i've made some changes to Town Of Us**

1.  ***✔️ Town Of Us Now Support 2024.3.5 Among Us Update***
2.  ***✔️Add Support for Long  player in shadows  from [Pietrodjaowjao](https://github.com/Pietrodjaowjao),  [Submerged Pull Request](https://github.com/SubmergedAmongUs/Submerged/pull/152)***
3. ***✔️Add an option to enable The new AprilFoolsMode***

### CODE REVIEW

**Comment by QaisZAK** [comment]
Bump

**Comment by whichtwix** [comment]
The devs work on the new version themselves, and the code from the submerged pr is not relevant to tour

**Comment by SaskueUchiwa** [comment]
so is this pull request will gonna get merged ?

**Comment by SaskueUchiwa** [comment]
if i need to remove something or add tell me

**Comment by MyDragonBreath** [comment]
closed due to releasing soon

**Pull request closed without merging**
