### PR TITLE
2.6.5 port for Among us 3.29

### PR DESCRIPTION
**Pull request by MyDragonBreath**
Hacky port for 2022.3.29,
~~Couldn't figure out how/(don't have time) to fix grenadier in the port.~~
~~Weird issues with HudManager's fullscreen sprite~~
fixed

You'll need to download the new Reactor artefact from [actions/runs/2076037814](https://github.com/NuclearPowered/Reactor/actions/runs/2076037814) and load that in BepInEx. (as well as update the nuget packages)

Hope if anything you find some of my code salvageable.

### CODE REVIEW

**Comment by MyDragonBreath** [comment]
Fixed grenadier. It was just setting the gameobject to active
i spent way too long looking for it.

port finished

**Comment by eDonnes124** [comment]
You see it's not as simple as that, we're also doing something... extra. I'll leave it at that.

**Comment by eDonnes124** [comment]
But thank you, I had 2 problems left which I hadn't been able to fix.

**Comment by OhMyGuus** [comment]
> ill keep looking if you think it will cause serious issues - but already with a few searches through dotPeek its looking a bit fruitless
No I don't think it will cause issues since Among us itself did some refactoring as well so they might as well fixed it since u tested it.
(and if the animation of the skin still accours randomly (for example after a transform etc) then you should use Hatmanager.GetSkinById(skinid).viewdata and compare that

**Pull request merged**
