### PR TITLE
Add information for juggernaut

### PR DESCRIPTION
**Pull request by marcoSchr**
This Pull request will add information about the Juggernaut role.
This will solve #95

### CODE REVIEW

**Comment by whichtwix** [comment]
its sort of meant to be a secret role, hence no info on here

**Comment by marcoSchr** [comment]
What is the advantage of keeping the role "secret"?

I only see a disadvantage, as every time someone gets the role, they ask, what it does exactly.
The ingame description is not informative enough and one can not point new players to the readme for the role, as it is not documented there.

**Comment by whichtwix** [comment]
its meant as a surprise for new players, and ig 1 reason it can be is lowering kill cd doesnt need explanation as much unlike any other role and it can still be noticeable

**Comment by eDonnes124** [comment]
Settings and an on/off switch for Hidden Roles and information will be available next update.

**Pull request closed without merging**
