### PR TITLE
Update modding tools

### PR DESCRIPTION
**Pull request by slyde99**
As many people (including myself) had trouble compiling this mod, I have replicated tools from [Reactor.Template](https://github.com/NuclearPowered/Reactor.Template) that does not require references from local Among Us folder. This changes optionally requires `AmongUs` environment variable to be set to the modded Among Us folder to copy the built `TownOfUs.dll` automatically during post-build event.

### CODE REVIEW

**Comment by slyde99** [comment]
Custom hats are not loaded for the lack of `Newtonsoft.Json.dll` from `mono/Managed`, fixing this issue inside this PR.

**Comment by slyde99** [comment]
Converted to `System.Text.Json` that came bundled with BepInEx, giving compatibility to the mod without `Newtonsoft.Json` as external library.

**Comment by VirusTLNR** [comment]
To be honest this would help people with working on tou.
https://github.com/VirusTLNR/Town-Of-Us/commit/c0e3cc1addb85f3da336bd7dad2f00ec26627ef7

By adding the bepinex repo to the configuration of tou-r, it will mean people still likely get errors.. (I still get them).

But.. every time I start a new pr after the above has been added.. 

I change the bepinex package version, then change it back, save  close, reopen, do the same for any other packages not registering correctly, one by one, save, close reopen.

After I have done this, it all works fine and I can work on the pr.

But without this nuget config, unless people manually add the bepinex repo, they will encounter errors they can't fix, at least if using visual studio..

Hope it helps.

**Comment by Bamaboy123455455** [comment]
I hope I did it

**Pull request closed without merging**
