### PR TITLE
Role Rework: Detective

### PR DESCRIPTION
**Pull request by taelspinner**
Detective is commonly cited as the worst and most boring role in lobbies. The primary reason for this is that its abilities revolve entirely around finding a body before anyone else does, which is luck and guesswork based at the best of times. At the same time, if you were able to inspect bodies at any time and unerringly find their killer, the role would easily go from tedious to wildly overpowered.

Therefore, in order to make this role more interesting while also keeping it balanced, I have taken some cues from the old Stellar Roles implementation of Detective to rework it. All code and assets are original. Here is how the Detective role now works:

- When a player dies, in addition to the body left behind, a "Crime Scene" is also created _**on the Detective player's client only,**_ not visible to any other players. This Crime Scene takes the form of a pool of blood under the body.
- When the body is cleaned up by a meeting, the Crime Scene remains for the rest of the game. Crime Scenes are, however, removed by a Janitor cleaning the body.
- A Crime Scene records a list of every player that has gotten near to it (I couldn't find a better method of doing this than using view distance, feel free to provide a superior method if you know one that will restrict it to collision with the sprite).
- The Inspect button now targets Crime Scenes instead of dead bodies. When a Detective Inspects a Crime Scene, the Examine button will store a list of all players that touched that crime scene _**before**_ the Detective Inspected it, overwriting any previous Inspection. The Detective cannot see this list.
- The Examine button will flash red when used on a player that is on the list, and green otherwise. If the Examine button flashes red, it will also log an informative message in the text chat for the next meeting.

The Detective's primary ability now revolves around getting to crime scenes as quickly as possible and inspecting them for clues, and then using that knowledge to narrow down who the killer might be. However, there is ambiguity in this information as anyone who touched the crime scene before you is a potential suspect. Rather than positively IDing the killer, the Detective role is primarily used to catch people in lies, e.g. if they claim that they weren't at the scene of the crime, you can confirm that they are lying.

The Detective is no longer pressured to find bodies before anyone else, but is still rewarded for doing so, as the only possible suspect will be the killer. This also creates opportunities for killers to cover their tracks, e.g. because the reporter will always show up as a potential suspect, making self-reports more powerful against Detectives. The Detective's secondary ability is unchanged.

XYM7Exr

### CODE REVIEW

**Comment by GameTechGuides** [comment]
Feature broken in 2024.3.5

**Comment by fariparedes** [comment]
> Feature broken in 2024.3.5

Can you elaborate? I have been using it without issue.

**Comment by GameTechGuides** [comment]
> > Feature broken in 2024.3.5
> 
> Can you elaborate? I have been using it without issue.

i try it on my modified version of tou and the i have the following issue : the button inspect and examine dosen't highlight when u are next to someone + the crime scene sang dosen't show up in the body

**Comment by GameTechGuides** [comment]
can i have your discord ? for more info

**Comment by fariparedes** [comment]
Updated for v5.0.4
I'm particularly fond of this one so I hope it makes it in :)

**Comment by eDonnes124** [comment]
Rework implemented for next patch.

**Pull request closed without merging**
