### PR TITLE
[WIP] change from killbutton to abilitybutton

### PR DESCRIPTION
**Pull request by whichtwix**
currently wip as there is a bug with no buttons appearing after hauntminigame.begin

right now imp/nk abilities are killbuttons, but the abilitybutton is unused apart from haunt so it may be good to change to using that, the patch to change their button becomes alike to how crew,nk, and arso/pb roles get theirs. this way all the sprite changing  could be in 1 file

- changing would firstly no longer need the extrabuttons list in Role and only glitch will have it. 
- In all imp roles the field and property relating to their killbutton can also be removed. 
- Performkill.cs and hudmanagerupdate.cs files are able to get simplified as instantiating is unneeded and the setactive code is now unified. Additionally, due to multiple killbuttons the patches needed checks like  ```if (__instance == role.ReviveButton)```, these are now redundant as theres only 1 abilitybutton
- abilities can be binded to the role ability keybind now

### CODE REVIEW

**Comment by AlchlcDvl** [comment]
conversely you could also make a custom button class and override the button's OnClick function so there's no need to patch AbilityButton.DoClick, plus if you add an effect parameter you can maybe make it work like the shapeshift button from the vanilla shapeshifter

**Comment by whichtwix** [comment]
the thing with that is it leads to the same thing, we will have to instanatiate that class and itll be mostly like before, and I dont think the do click will run on its own without a patch unless we go the rainbow route and do the registerinil2cpp stuff, will have to look into how that way is

**Comment by whichtwix** [comment]
clicking haunt a 2nd time made the buttons appear but the minigame would technically close,  found a quite sketchy way to fix it by inverting the close states, though you still have to click it multiple times

**Comment by AlchlcDvl** [comment]
> the thing with that is it leads to the same thing, we will have to instanatiate that class and itll be mostly like before, and I dont think the do click will run on its own without a patch unless we go the rainbow route and do the registerinil2cpp stuff, will have to look into how that way is

nah i made a quick class and checked it out, there's no need for patches

**Comment by whichtwix** [comment]
hmm ok, though in that case overriding useability from rolebehavior may be better, since the doclick runs that within its method, and there are other methods in rolebehavior that may be helpful

**Pull request closed without merging**
