### PR TITLE
Better custom options

### PR DESCRIPTION
**Pull request by AlchlcDvl**
Contains
- Some more save/loading slots
- ~~Setting looping, meaning going over the max will loop the setting to its minimum value and vice versa~~ Added in 4.0.4
- Added preset loading, with default and last used settings being example presets
- Added nested option menus
- Removed the Glitch hack distance option because it's kind of redundant
- Optimised some parts of the settings code
- Added a new format for distances
- Added the ability to jump to specific pages
- Most number options can now be halved, as long as the increase is greater than 1
- Readjusted role alignments like in #135 
- The game now saves and updates settings everyone time one opens or closes the game
- Changing the game aspect no longer cuts off the settings from the screen
- Added a little nice looking change to how the settings appear in lobby

If fully implemented, I suggest also adding #144 to go along with it

### CODE REVIEW

**Comment by eDonnes124** [comment]
Loading the set presets such as the 'default' one provided doesn't work, tried several times.

**Comment by AlchlcDvl** [comment]
ah, i'll try and fix it

**Comment by AlchlcDvl** [comment]
This one i though I had to do because the hack distance option would have made sense if all forms of interaction had their own distance settings but since it's not the case, the option's kind of obsolete

**Comment by AlchlcDvl** [comment]
with this i'm done with the custom game options lol, next one might be just adding more options for customisation purposes

**Pull request closed without merging**
