### PR TITLE
Update to Among us 2023.7.11

### PR DESCRIPTION
**Pull request by JeanAU**
hey @eDonnes124 i was worked on TOU to update to Latest version of Among us so there a few changes :

1. _**Add Support Latest Verison**_  ✔️ 

2. _**Add Custom Annoncements**_ ✔️ 
3. _**Test it**_ ✔️  all works sucess

i wish to merge this pull-request and Good Luck 😄  

Contact Me in discord : jeanamongus

### CODE REVIEW

**Comment by AlchlcDvl** [comment]
ResolutionManager.ResolutionChanged.Invoke((float)Screen.width / Screen.height);

can be changed to

ResolutionManager.ResolutionChanged.Invoke((float)Screen.width / Screen.height, Screen.width, Screen.height, Screen.fullScreen);

**Comment by JeanAU** [comment]
@eDonnes124  when this pull get merged 😄

**Comment by Liimiitz** [comment]
Just tested the new dll file after building and can confirm it works  
image
image

**Comment by JeanAU** [comment]
@Liimiitz Contact me in discord plz i have something to tell you discord : jeanamongus

**Comment by whichtwix** [comment]
btw likely wont be merged, the mod has been made comptaible already but other things are going on, the custom announcements may or may not be added after its closed

**Comment by JeanAU** [comment]
> btw likely wont be merged, the mod has been made comptaible already but other things are going on, the custom announcements may or may not be added after its closed

but why ? Custom Annoucement is very good idea and i add support for AU 2023.7.11

**Comment by JeanAU** [comment]
I wante really join developement i have in stock many ideas that i can do it 😄

**Comment by AlchlcDvl** [comment]
well from my communications with mdb, they're fine with being only 2 devs so sadly there won't be any openings for now

**Comment by whichtwix** [comment]
if you have any ideas feel free to make them then make a pull request here, it may get seen and added

> but why ? Custom Annoucement is very good idea and i add support for AU 2023.7.11
i meant there is chance of it being added

**Comment by JeanAU** [comment]
@eDonnes124 did you see this pull if yes send an message please

**Comment by JeanAU** [comment]
hey @MyDragonBreath  is something in this pull-request will be in next version of TOU ? and thanks 😄

**Comment by MyDragonBreath** [comment]
as a bit of constructive feedback - from a thing you may have overlooked regarding properly testing the transporter menu.
there was an error that needed to be patched out with the set visible method. 
when i did it weeks ago i chose to 
```
[HarmonyPatch(typeof(ChatController), nameof(ChatController.UpdateChatMode))]
    class chatModeUpdate
    {
        private static bool Prefix(ChatController __instance)
        {
            if (!PlayerControl.LocalPlayer.Is(RoleEnum.Transporter)) return true;
            return (__instance != Role.GetRole<Transporter>(PlayerControl.LocalPlayer).TransportList);
        }
    }

 ```

**Comment by MyDragonBreath** [comment]
please do not ghost ping donners (or myself for that matter).
apologies, we both have lives beyond this and it takes a while to get around to everything.

we have long since finished porting, and are currently working on the next update. 
Thankyou for your effort.

if you change an asset file (arrow.png) please indicate why/(or that you've even done it).

the mod news may be merged, but i don't like the idea of having to hardcode each version in. If it is merged in later, it will most likely have to be in a json/resource file format from the embedded resources, or pulled from github at runtime.

i will close this for now, but feel free to make a separate pr for modnews

**Pull request closed without merging**
