### PR TITLE
End Game Summary improvement + New Buttons

### PR DESCRIPTION
**Pull request by itsjesushx**
This PR adds death reasons to the end game summary, the summary is also reduced in size so the ''Victory'' text doesnt bother the summary. I also added new buttons to replace the ones that look very old.

### CODE REVIEW

**Comment by GameTechGuides** [comment]
@Jsushi07 hey i like the new buttons style are you the creator of thoses button ? can u make a button for a special role that i make

**Comment by Jsushi07** [comment]
actually I didn't make them, it was an old friend of mine that made them

**Comment by GameTechGuides** [comment]
ah ok what's your discord ? i saw you making cool stuff to tou

**Comment by Jsushi07** [comment]
What do you need my discord for 🗿

**Comment by Loonie-Toons** [comment]
For the buttons specifically, why not use the Among Us font that's used in many places of the game (such as for buttons and some UI). 
image

**Pull request closed without merging**
