### PR TITLE
Option: Experimental Horse Setting

### PR DESCRIPTION
**Pull request by MyDragonBreath**
Adds a setting to turn everyone to horses
it works for the most part...

If anything I hope you find some of this useful - I know Twix suggested it in an issue so I decided to try my hand at implementing it

Known bugs:
hat animations
skins on player loading in after setting has been enabled (fixes upon start game tho)

### CODE REVIEW

**Comment by ItsTheNumberH** [comment]
Would it not be more practical to use `Constants.ShouldHorseAround`?
e.g.
`
        [HarmonyPatch(typeof(Constants), nameof(Constants.ShouldHorseAround))]
        public static class ShouldAlwaysHorseAround {
            public static bool Prefix(ref bool __result) {
                __result = CustomGameOptions.Horse;
                return false;
            }
        }`

**Comment by MyDragonBreath** [comment]
Does that work? I assumed you could only have that patch run on game start

if so ill close the pr

**Comment by ItsTheNumberH** [comment]
It does work - though you are right, it only runs on game start. Your code will update it on change. Worth keeping your change if it's wanted to be an immediate change

**Comment by MyDragonBreath** [comment]
I did make a build with that same harmony patch that i used for a bit of fun once - 
but I didn't know whether its worth rebuilding for each version. 
(from the fact that its a constant function i assume the code is staying and check the date. )

**Comment by whichtwix** [comment]
idk if this is a thing or not, but can you make this thing trigger on joining a lobby or some other similar change, and itll look at the setting, itll be a mix of both your methods ig

with this, if it is possible, itd still be a little tedious, im thinking the person would have to go settings, enable or disable, and rejoin lobby

**Comment by MyDragonBreath** [comment]
ill close this pr and open a new one with the new changes

**Pull request closed without merging**
