### PR TITLE
Support for V2021.9.11

### PR DESCRIPTION
**Pull request by OhMyGuus**
I updated this fork to V2021.9.11 and u can use it basically fully or some parts of it!

### CODE REVIEW

**Comment by OhMyGuus** [comment]
For any1 who wants to test this: 
https://github.com/OhMyGuus/Town-Of-Us-R/releases/tag/v2021.9.11

**Comment by OhMyGuus** [comment]
Fixed a couple issues that someone noticed for people who where testing this redownload it.

**Comment by OhMyGuus** [comment]
Just a small note: 
When u test this or try to implement this make sure you updated bepinex otherwise it won't work. It is tested on the one that's in my release which is version: 6.0.0-be.518 & with the Newtonsoft.Json.dll in the mono/managed folder.

**Comment by whichtwix** [comment]
putting bugs that are found within this pr. First one about glitch. 
Glitch has a kill button while in the meeting, and can kill so long as their cooldown is up.

Glitch

Just be glitch, get in a meeting and go ham.

No solutions other than to turn glitch off, really.
image

**Comment by whichtwix** [comment]
engineer

1. has imp vision
2. has a sab button instead of fix, but it does fix sabs
3. cannot use vents
in relation the the engi thing, they get an "Imposter" screen and then "Engineer" instead of "Crewmate" -> "Engineer"
image

impostosr have a visual bug on skeld
image

**Comment by OhMyGuus** [comment]
> putting bugs that are found within this pr. First one about glitch. Glitch has a kill button while in the meeting, and can kill so long as their cooldown is up.
> 
> Glitch
> 
> 1. hack and mimic are stacked on eachother, either can be used
> 2. can kill in meetings
> 
> No solutions other than to turn glitch off, really. image

thanks apparently the buttons where bound towards the usebutton being visible (which is visible in the meeting now)

**Comment by whichtwix** [comment]
seems the morphling has stacking problems, but not all the time

**Comment by OhMyGuus** [comment]
All those issues should be fixed now and is in Town.Of.Us.2-3-4-test-6

**Comment by whichtwix** [comment]
in the kill animation swooper is shown as a red crewmate with no cosmetics which may confuse a revived player

**Comment by MatadorProBr** [comment]
It seems that buttons are getting overlayed on the kill button and you can get 2 roles at the same time.


<hr />

*Originally reported by `PyroTech03#1491` on TOU-R Discord.*
*If you want to see the original message on Discord, click [here](https://discord.com/channels/890249154402586734/900991929632821288/911434551354609715).*

**Comment by whichtwix** [comment]
adding intense lag for EVERYONE when haunter/phantom spawns or camo comms is called, and lag for imp/glitch when snitch alert is triggered

**Comment by OhMyGuus** [comment]
Tested it now with a group and everything is working now and the lagg etc is fixed. 
So I think this pr can almost get merged (be aware click on squash and merge when u merge since it are a lot of commits)

**Pull request merged**
